import type {ProductMaster} from "chums-types";

export const newProduct:ProductMaster = {
    id: 0,
    company: 'chums',
    devCode: '',
    name: '',
    status: {new: true},
    active: true,
    productType: 'F',
    productLine: null,
    category: null,
    subCategory: null,
    idSKUGroup: 0,
    SKU: '',
    UPC: '',
    sellAsSelf: true,
    sellAsMix: true,
    sellAsColors: true,
    color: null,
    suggestedRetailPrice: 0,
    stdPrice: 0,
    stdCost: 0,
    notes: null,
    userId: null,
    dateCreated: '',
    dateUpdated: '',
    season: null,
}
