import {get, LS_PRODUCT_LIST_UI} from '../utils/localStorage';

export const FETCH_INIT = 'FETCH_INIT';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const FETCH_VERSION = 'FETCH_VERSION';

export const SET_ALERT = 'SET_ALERT';
export const DISMISS_ALERT = 'DISMISS_ALERT';

export const SET_COMPANY = 'SET_COMPANY';

export const FETCH_USER_ROLES = 'FETCH_USER_ROLES';
export const RECEIVE_USER_ROLES = 'RECEIVE_USER_ROLES';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';

export const SAVE_ATTRIBUTES = 'SAVE_ATTRIBUTES';
export const SAVE_ATTRIBUTES_FAILURE = 'SAVE_ATTRIBUTES_FAILURE';
export const RECEIVE_ATTRIBUTES = 'RECEIVE_ATTRIBUTES';

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT_LIST_FAILURE = 'FETCH_PRODUCT_LIST_FAILURE';
export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ATTRIBUTES = 'UPDATE_PRODUCT_ATTRIBUTES';

export const SELECT_SEASON = 'SELECT_SEASON';
export const UPDATE_SEASON = 'UPDATE_SEASON';
export const FETCH_SEASONS = 'FETCH_SEASONS';
export const FETCH_SAVE_SEASON = 'FETCH_SAVE_SEASON';

export const SET_PRODUCT_LIST_UI = 'SET_PRODUCT_LIST_UI';
export const SET_PRODUCT_MAIN_UI = 'SET_PRODUCT_MAIN_UI';

export const FETCH_PRODUCT_ITEMS = 'FETCH_PRODUCT_ITEMS';

export const SET_PRODUCT_SECTION = 'SET_PRODUCT_SECTION';







